export const applications = [
  {
    companyName: 'Company A',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2023',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company B',
    jobTitle: 'Product Manager',
    applicationDate: '20/10/2023',
    currentStage: 'Screening',
    location: 'San Francisco',
    source: 'Indeed',
  },
  {
    companyName: 'Company C',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company D',
    jobTitle: 'Software Engineer',
    applicationDate: '06/04/2024',
    currentStage: 'Screening',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company E',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Screening',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company F',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company G',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company H',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Screening',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company I',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company J',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company K',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Screening',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company L',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company M',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Interview',
    location: 'New York',
    source: 'LinkedIn',
  },
  {
    companyName: 'Company N',
    jobTitle: 'Software Engineer',
    applicationDate: '01/10/2024',
    currentStage: 'Screening',
    location: 'New York',
    source: 'LinkedIn',
  }
]